M48
; DRILL file {KiCad 7.0.7} date 2024 August 26, Monday 03:28:38
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-26T03:28:38+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0266
%
G90
G05
T1
X6.2343Y-2.6699
T2
X6.2343Y-2.9533
T0
M30
