M48
; DRILL file {KiCad 7.0.2} date Tue Oct 17 11:37:12 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-17T11:37:12+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.675
%
G90
G05
T1
X177.55Y-67.815
T2
X177.55Y-75.015
T0
M30
